version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: expo
    versions:
    - ">= 40.a, < 41"
  - dependency-name: expo
    versions:
    - 39.0.5
    - 41.0.0
  - dependency-name: metro-react-native-babel-preset
    versions:
    - 0.65.0
    - 0.65.2
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: flow-bin
    versions:
    - 0.143.1
    - 0.144.0
    - 0.145.0
    - 0.146.0
    - 0.147.0
    - 0.148.0
  - dependency-name: "@types/react-native"
    versions:
    - 0.63.50
    - 0.63.51
    - 0.64.0
    - 0.64.1
    - 0.64.2
  - dependency-name: "@expo/webpack-config"
    versions:
    - 0.12.63
  - dependency-name: react-test-renderer
    versions:
    - 17.0.1
  - dependency-name: react-native
    versions:
    - 0.64.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: semantic-release
    versions:
    - 17.3.7
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.2.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
  - dependency-name: eslint
    versions:
    - 7.18.0
